// =================================================================
// Jenkinsfile  —  generated by DevOps Pipeline Platform
// App: some  |  Type: java
// =================================================================
pipeline {
  agent any

  options {
    buildDiscarder(logRotator(numToKeepStr: '20'))
    timeout(time: 60, unit: 'MINUTES')
  }

  environment {
    APP_NAME    = 'some'
    APP_VERSION = '1.0.0'
  }

  // push / pull_request: configure an SCM webhook on the repo to trigger builds,
  // or add  triggers { pollSCM('H/5 * * * *') }  to poll for changes instead.

  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/sahil-ondc/test-pipeline.git'
      }
    }
    stage('Build') {
      steps {
        sh 'echo no build command configured'
      }
    }
    stage('Test') {
      steps {
        // Coverage gate: 80% (enforced inside the test script)
        sh 'echo no test command configured'
      }
    }
    stage('SonarQube Analysis') {
      when { expression { return false } }
      steps {
        echo 'Stage disabled by platform config (ci.scan.*.enabled=false) — skipped.'
      }
    }
    stage('Checkmarx SAST') {
      when { expression { return false } }
      steps {
        echo 'Stage disabled by platform config (ci.scan.*.enabled=false) — skipped.'
      }
    }
    stage('Architecture-as-Code') {
      when { expression { return false } }
      steps {
        echo 'Stage disabled by platform config (ci.scan.*.enabled=false) — skipped.'
      }
    }
  }

  post {
    always {
      echo "Pipeline finished with status: ${currentBuild.currentResult}"
    }
  }
}
